- name: Deploy Gitea with Docker
  hosts: 192.168.200.125
  become: true
  remote_user: "{{ ansible_ssh_user }}"  # Usando la variable ansible_ssh_user

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Create data directory for Gitea
      file:
        path: "{{ gitea_data_path }}"
        state: directory
        mode: "0755"

    - name: Stop existing Gitea container if exists
      shell: docker rm -f gitea 2>/dev/null || true
      args:
        warn: false

    - name: Deploy Gitea container
      shell: |
        docker run -d --name gitea \
          --restart unless-stopped \
          -p {{ gitea_port }}:3052 \
          -e GITEA__server__DOMAIN="{{ gitea_domain }}" \
          -e GITEA__security__INSTALL_LOCK="true" \
          -e GITEA__database__DB_TYPE="sqlite3" \
          -e GITEA__database__PATH="{{ gitea_data_path }}/gitea.db" \
          -e GITEA__security__SECRET_KEY="random_secret_key" \
          -e GITEA__security__INTERNAL_TOKEN="random_internal_token" \
          -v {{ gitea_data_path }}:/data \
          gitea/gitea:latest
      args:
        warn: false
