---
- name: Deploy Gitea container
  hosts: gitea
  become: yes
  vars:
    gitea_image: "gitea/gitea:latest"
    gitea_http_port: "{{ gitea_port }}"
    gitea_domain: "{{ gitea_domain }}"
    gitea_admin_user: "{{ gitea_admin_user }}"
    gitea_admin_password: "{{ gitea_admin_password }}"
  
  tasks:
    - name: Pull the Gitea Docker image
      docker_image:
        name: "{{ gitea_image }}"
        source: pull

    - name: Create a Gitea Docker container
      docker_container:
        name: gitea
        image: "{{ gitea_image }}"
        state: started
        restart_policy: always
        published_ports:
          - "{{ gitea_http_port }}:3052"
        env:
          GITEA_HTTP_PORT: "{{ gitea_http_port }}"
          GITEA_DOMAIN: "{{ gitea_domain }}"
          GITEA_ADMIN_USER: "{{ gitea_admin_user }}"
          GITEA_ADMIN_PASSWORD: "{{ gitea_admin_password }}"
        volumes:
          - /data/gitea:/data
        networks:
          - gitea_network
        log_driver: json-file
        log_options:
          max-size: "10m"
          max-file: "3"

    - name: Wait for Gitea to be up and running
      wait_for:
        port: "{{ gitea_http_port }}"
        delay: 10
        timeout: 60

    - name: Ensure Gitea is accessible
      uri:
        url: "http://{{ gitea_domain }}:{{ gitea_http_port }}"
        method: GET
        status_code: 200
        return_content: yes
      register: gitea_status

    - name: Display Gitea status
      debug:
        var: gitea_status.content

